name: Bug report
description: Report typos, broken links, or other documentation errors
title: 'Learning Center bug report'
labels: ["bug"]
assignees:
  - jkonrath-postman
body:
- type: checkboxes
  attributes:
    label: Is this an issue with the Learning Center documentation?
    description: This isn't a general support repo. For app support issues, please open an issue at [Postman App Support issues](https://github.com/postmanlabs/postman-app-support/issues).
    options:
    - label: This is an issue with Learning Center documentation.
      required: true
- type: textarea
  attributes:
    label: Describe the issue
    description: |
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Pages affected
    description: |
      If possible, list URLs of pages where the error occurs.
- type: textarea
  attributes:
    label: Screenshots
    description: |
      If applicable, add screenshots to help explain the issue.
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the problem here.
